//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.01.22 at 12:29:16 PM IST 
//


package com.comcast.commercial.common.message.types;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for RequestStatus.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="RequestStatus">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="TRANSFORMED_REQUEST"/>
 *     &lt;enumeration value="REQUEST_SUBMITTED"/>
 *     &lt;enumeration value="RESPONSE_RECEIVED_OM"/>
 *     &lt;enumeration value="OM_SERVICE_NOT_REACHABLE"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "RequestStatus")
@XmlEnum
public enum RequestStatus {

    TRANSFORMED_REQUEST,
    REQUEST_SUBMITTED,
    RESPONSE_RECEIVED_OM,
    OM_SERVICE_NOT_REACHABLE;

    public String value() {
        return name();
    }

    public static RequestStatus fromValue(String v) {
        return valueOf(v);
    }

}
